jb_tools/Models/IemuTranDetails.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace jb_tools.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IemuTranDetails
    {
        public int Id { get; set; }
        public string No { get; set; }
        public string Seq { get; set; }
        public string MainCode { get; set; }
        public string ScId { get; set; }
        public string DetailOrder { get; set; }
        public string Program { get; set; }
        public string Name { get; set; }
        public string Ename { get; set; }
        public string ProgramPath { get; set; }
        public string Remark { get; set; }
    }
}

jb_tools/Controllers/IemuTranDetailController.cs
using DocumentFormat.OpenXml.Wordprocessing;
using jb_tools.Models;
using jb_tools.Models.ViewModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DocumentFormat.OpenXml.EMMA;
using PagedList;
using System.Drawing.Printing;
using DocumentFormat.OpenXml.Bibliography;
using DocumentFormat.OpenXml.Spreadsheet;
using Microsoft.Ajax.Utilities;

namespace jb_tools.Controllers
{
    public class IemuTranDetailController : Controller
    {
        // for DropDownList ↓ -----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
        // Jacky 1120731

        // 第一層下拉選單原始資料結構
        List<vmDDLMainCodeModel> firstLevelRawItems = new List<vmDDLMainCodeModel>();
        public List<vmDDLMainCodeModel> FirstLevelRawItems { get => firstLevelRawItems; set => firstLevelRawItems = value; }
        
        // 第二層下拉選單原始資料結構
        List<vmDDLScIdModel> secondLevelRawItems = new List<vmDDLScIdModel>();
        public List<vmDDLScIdModel> SecondLevelRawItems { get => secondLevelRawItems; set => secondLevelRawItems = value; }

        // 第三層下拉選單原始資料結構
        List<vmDDLDetailOrderModel> thirdLevelRawItems = new List<vmDDLDetailOrderModel>();
        public List<vmDDLDetailOrderModel> ThirdLevelRawItems { get => thirdLevelRawItems; set => thirdLevelRawItems = value; }

        /// <summary>
        /// 準備下拉選單的資料
        /// </summary>
        /// <param name="id"></param>
        private void PrepareDropDownList(int id = 0)
        {
            // 第一層被選定的大分類代號
            string selectedMainCode = string.Empty;

            // 第二層被選定的中分類識別
            string selectedScId = string.Empty;

            // 第三層被選定的細分類序號
            string selectedDetailOrder = string.Empty;

            // -------------------------------------------------- ↓ 建立原始資料來源 ↓ --------------------------------------------------
            // 建立第一層原始資料來源
            using (z_repoIemuMainMenus iemuMainMenus = new z_repoIemuMainMenus())
            {
                // 建立第一層 ViewModel 資料，以 IemuMainMenus 資料表的資料，來建立第一層 ViewModel 資料，作為下拉選單呈現的資料
                foreach (var row in iemuMainMenus.GetDapperDataList(""))
                {
                    FirstLevelRawItems.Add(
                        new vmDDLMainCodeModel()
                        {
                            MainCode = row.MainCode,
                            McId = row.McId,
                            Name = row.Name,
                            SortNum = row.SortNum
                        }
                    );
                }

                // Jacky 1120806 儲存第一層原始資料來源
                Session["FirstLevelRawItems"] = FirstLevelRawItems;
            }

            // 第二層原始資料來源
            using (z_repoIemuSubMenus iemuSubMenus = new z_repoIemuSubMenus())
            {
                // 建立第二層 ViewModel 資料，以 IemuSubMenus 資料表的資料，來建立第二層 ViewModel 資料，作為下拉選單呈現的資料
                foreach (var row in iemuSubMenus.GetDapperDataList(""))
                {
                    SecondLevelRawItems.Add(
                        new vmDDLScIdModel()
                        {
                            SubCode = row.SubCode,
                            ScId = row.ScId,
                            Name = row.Name,
                            MainCode = row.MainCode,
                            SortNum = row.SortNum
                        }
                    );
                }

                // Jacky 1120806 儲存第二層原始資料來源
                Session["SecondLevelRawItems"] = SecondLevelRawItems;
            }

            // 第三層原始資料來源
            using (z_repoIemuDetailMenus iemuDetailMenus = new z_repoIemuDetailMenus())
            {
                // 建立第三層 ViewModel 資料，以 IemuDetailMenus 資料表的資料，來建立第三層 ViewModel 資料，作為下拉選單呈現的資料
                foreach (var row in iemuDetailMenus.GetDapperDataList(""))
                {
                    ThirdLevelRawItems.Add(
                        new vmDDLDetailOrderModel()
                        {
                            DetailOrder = row.DetailOrder,
                            Program = row.Program,
                            Name = row.Name,
                            ProgramPath = row.ProgramPath,
                            ScId = row.ScId,
                            MainCode = row.MainCode,
                            SortNum = row.SortNum
                        }
                    );
                }

                // Jacky 1120806 儲存第三層原始資料來源
                Session["ThirdLevelRawItems"] = ThirdLevelRawItems;
            }
            // -------------------------------------------------- ↑ 建立原始資料來源 ↑ --------------------------------------------------

            // -------------------------------------------------- ↓ 大分類 ↓ --------------------------------------------------
            if (id == 0)
            {
                // 1. 找出第一筆當作預設的 MainCode
                selectedMainCode = (
                    from f in FirstLevelRawItems
                    orderby f.SortNum
                    select f.MainCode
                    ).FirstOrDefault();
            }
            else
            {
                // 1. 找出表身 IemuTranDetails 該筆資料的 Id 之 MainCode、ScId、DetailOrder
                using (z_repoIemuTranDetails iemuTranDetails = new z_repoIemuTranDetails())
                {
                    var data = iemuTranDetails.GetDapperData(id);
                    selectedMainCode = data.MainCode;
                    selectedScId = data.ScId;
                    selectedDetailOrder = data.DetailOrder;
                }
            }

            // 2. 用 LINQ 撈出第一層原始資料來源，用以建立 SelectListItem 實例
            var items =
                (
                    (
                        // 設定 [預設選取] 的下拉選單內容 
                        from f in FirstLevelRawItems
                        where f.MainCode == selectedMainCode
                        select new SelectListItem
                        {
                            Text = f.MainCode + SelectListService.Delimiter + f.McId + SelectListService.Delimiter + f.Name,
                            Value = f.MainCode,
                            Selected = true
                        }
                    )
                    .Union
                    (
                        // 設定 [非預設選取] 的下拉選單內容 
                        from f in FirstLevelRawItems
                        where f.MainCode != selectedMainCode
                        orderby f.SortNum
                        select new SelectListItem
                        {
                            Text = f.MainCode + SelectListService.Delimiter + f.McId + SelectListService.Delimiter + f.Name,
                            Value = f.MainCode,
                            Selected = false
                        }
                    )
                ).ToList();

            // 3. 第一層原始資料來源建立的下拉選單資料，存入 ViewData
            Session["FirstLevelItems"] = items;
            // -------------------------------------------------- ↑ 大分類 ↑ --------------------------------------------------

            // -------------------------------------------------- ↓ 中分類 ↓ --------------------------------------------------
            if (id == 0)
            {
                // 1. 以 MainCode == selectedMainCode 為條件，找出第一筆的 ScId 
                selectedScId = (
                    from s in SecondLevelRawItems
                    where s.MainCode == selectedMainCode
                    orderby s.SortNum
                    select s.ScId
                    ).FirstOrDefault();
            }
            else
            {
                // 1. 已於第一層取得 selectedScid
            }

            // 2. 用 LINQ 撈出第二層原始資料來源，用以建立 SelectListItem 實例
            items =
            (
                (
                    // 設定 [預設選取] 的下拉選單內容 
                    from s in SecondLevelRawItems
                    where s.ScId == selectedScId && s.MainCode == selectedMainCode
                    select new SelectListItem
                    {
                        Text = s.ScId + SelectListService.Delimiter + s.SubCode + SelectListService.Delimiter + s.Name,
                        Value = s.ScId,
                        Selected = true
                    }
                )
                .Union
                (
                    // 設定 [非預設選取] 的下拉選單內容 
                    from s in SecondLevelRawItems
                    where s.ScId != selectedScId && s.MainCode == selectedMainCode
                    orderby s.SortNum
                    select new SelectListItem
                    {
                        Text = s.ScId + SelectListService.Delimiter + s.SubCode + SelectListService.Delimiter + s.Name,
                        Value = s.ScId,
                        Selected = false
                    }
                )
            ).ToList();

            // 3.a. 第二層原始資料來源建立的下拉選單資料，存入 ViewData
            ViewData["SecondLevelItems"] = items;
            // 3.b. 記錄預設的 ScId
            ViewBag.SelectedScId = selectedScId;
            // -------------------------------------------------- ↑ 中分類 ↑ --------------------------------------------------

            // -------------------------------------------------- ↓ 細分類 ↓ --------------------------------------------------
            if (id == 0)
            {
                // 1. 以 MainCode == selectedMainCode + ScId == selectedScId 為條件，找出第一筆的 DetailOrder
                selectedDetailOrder = (
                    from t in ThirdLevelRawItems
                    where t.ScId == selectedScId && t.MainCode == selectedMainCode
                    orderby t.SortNum
                    select t.DetailOrder
                    ).FirstOrDefault();
            }
            else
            {
                // 1. 已於第一層取得 selectedDetailOrder
            }

            // 2. 用 LINQ 撈出第三層原始資料來源，用以建立 SelectListItem 實例
            items =

jb_tools/Views/IemuTranDetail/CreateEdit.cshtml
@using jb_tools.Models.ViewModel;
@model vmIemuTranDetailCreateEdit

@{
    ViewBag.Title = "CreateEdit";
    Layout = "~/Views/Shared/_LayoutCardIemuTranDetail.cshtml";
    ActionService.RowId = Model.IemuTranDetailsModel.Id;

    // 取得目前的編輯模式
    var editMode = ViewBag.Action;

    //List<SelectListItem> mainCodeList = new List<SelectListItem>();
    //using (ListItemData listData = new ListItemData())
    //{
    //    mainCodeList = listData.MainCodeList();
    //}
}

<script type="text/javascript">
    $(document).ready(init);

    function init() {
        // 準備 DropDownList 相關資訊
        //PrepareDropDownList();

        // 當網頁上的 DOM 都載入時，第一層下拉選單也呈現出來了
        // ↓顯示第二層下拉選單，沒加這兩段↓的話，第一次網頁載入時第二層下拉選單不會出現

        // 取得第一層選擇的值
        var mainCode = $("select[name = 'IemuTranDetailsModel.MainCode']").val();
        console.log('1 val: mainCode: ' + mainCode);

        // 取得第二層選擇的值
        var scId = $("select[name = 'vmDDLScIdModel.ScId']").val();
        console.log('1 val: scId: ' + scId);

        // 取得第三層選擇的值
        var detailOrder = $("select[name = 'vmDDLDetailOrderModel.DetailOrder']").val();
        console.log('1 val: detailOrder: ' + detailOrder);

        // 為第一層下拉選單註冊 onchange 事件
        $("select[name = 'IemuTranDetailsModel.MainCode']").change(function () {
            // 取得第一層選擇的值
            var mainCode = $(this).val();
            console.log('2 val: mainCode: ' + mainCode);

            // 取得第二層選擇的值
            var scId = '@ViewBag.SelectedScId.ToString()';
            console.log('2 SelectedScId: scId: ' + scId);

            // 取得第二層變數
            var $selectScId = $("select[name = 'vmDDLScIdModel.ScId']");

            // 重新觸發第二層下拉選單
            $selectScId.change();
        });

        // 為第二層下拉選單註冊 onchange 事件
        $("select[name = 'vmDDLScIdModel.ScId']").change(function () {
            // 取得第一層選擇的值
            var mainCode = $("select[name = 'IemuTranDetailsModel.MainCode']").val();
            console.log('3 val: mainCode: ' + mainCode);

            // 取得第二層的值
            var scId = $("select[name = 'vmDDLScIdModel.ScId']").val();
            console.log('3 val: scId: ' + scId);

            // test => print command
            console.log('3 SetSecondDropDownList(' + mainCode + ', ' + scId + ')');

            // 設定第二層下拉選單
            SetSecondDropDownList(mainCode, scId);

            // 取得第三層變數
            var $selectDetailOrder = $("select[name = 'vmDDLDetailOrderModel.DetailOrder']");

            // 重新觸發第三層下拉選單
            $selectDetailOrder.change();
        });

        // 為第三層下拉選單註冊 onchange 事件
        $("select[name = 'vmDDLDetailOrderModel.DetailOrder']").change(function () {
            // 取得第一層選擇的值
            var mainCode = $("select[name = 'IemuTranDetailsModel.MainCode']").val();
            console.log('4 val: mainCode: ' + mainCode);

            // 取得第二層選擇的值
            var scId = $("select[name = 'vmDDLScIdModel.ScId']").val();
            console.log('4 val: scId: ' + scId);

            // 取得第三層選擇的值
            var detailOrder = $("select[name = 'vmDDLDetailOrderModel.DetailOrder']").val();
            console.log('4 val: detailOrder: ' + detailOrder);

            // test => print command
            console.log('4 SetThirdDropDownList(' + mainCode + ', ' + scId + ', ' + detailOrder + ')');

            // 設定第三層下拉選單
            SetThirdDropDownList(mainCode, scId, detailOrder);
            var detailOrder = '@ViewBag.SelectedDetailOrder.ToString()';
            console.log('4 SetThirdDropDownList: detailOrder: ' + detailOrder);
        });
    }

    function SetSecondDropDownList(mainCode, scId) {
        $.ajax({
            catch: false,
            url: '@Url.Action("SetSecondDropDownList", "IemuTranDetail")',
            type: "get",
            data: { mainCode: mainCode, scId: scId },
            async: false,
            success: function (result) {
                $("select[name = 'vmDDLScIdModel.ScId']").empty().html(result);
            }
        });
    }

    function SetThirdDropDownList(mainCode, scId, detailOrder) {
        $.ajax({
            catch: false,
            url: '@Url.Action("SetThirdDropDownList", "IemuTranDetail")',
            type: "get",
            data: { mainCode: mainCode, scId: scId, detailOrder: detailOrder },
            async: false,
            success: function (result) {
                $("select[name = 'vmDDLDetailOrderModel.DetailOrder']").empty().html(result);
            }
        });
    }
</script>

<div class="card mt-5 shadow w-50">
    <div class="card-header text-white bg-primary">
        <div class="d-flex justify-content-center">
            @if (editMode == enAction.Create)
            {
                <h3>編輯 IEMenu - 交易表單 - 明細 - @ActionService.CreateName</h3>
            }
            else
            {
                <h3>編輯 IEMenu - 交易表單 - 明細 - @ActionService.EditName</h3>
            }
        </div>
    </div>
    <div class="card-body pt-4">
        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal mt-2">
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                @Html.HiddenFor(m => m.IemuTranDetailsModel.Id)

                @* 單號 *@
                <!--<div class="row form-group mb-1">
                @Html.LabelFor(m => m.IemuTranDetailsModel.No, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">-->
                @* 注意：這裡只能用 readoly 不能用 disabled，因為會被 Form Submit 忽略之，也就是不會傳送至 Server *@
                @* readonly 用法：@readonly = true，但是元素 <SELECT> <OPTION> <BUTTON> 不支援 readonly *@
                @* disabled 用法：disabled = "disabled" *@
                <!--@Html.EditorFor(m => m.IemuTranDetailsModel.No, new { htmlAttributes = new { @class = "form-control readonly_bgc", @readonly = true } })
                        @Html.ValidationMessageFor(m => m.IemuTranDetailsModel.No, "", new { @class = "text-danger" })
                    </div>
                </div>-->
                @* 項次 *@
                <div class="row form-group mb-1">
                    @Html.LabelFor(m => m.IemuTranDetailsModel.Seq, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(m => m.IemuTranDetailsModel.Seq, new { htmlAttributes = new { @class = "form-control readonly_bgc", @readonly = true } })
                        @Html.ValidationMessageFor(m => m.IemuTranDetailsModel.Seq, "", new { @class = "text-danger" })
                    </div>
                </div>

                @* 大分類代號 *@
                <div class="row form-group mb-1">
                    @Html.LabelFor(m => m.IemuTranDetailsModel.MainCode, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @* Jacky 1120807 因為第一層下拉選單內容不會改變，所以這裡直接顯示內容資料即可，不需要以 PartialView 的方式去整合動態資料 *@
                        @Html.DropDownListFor(m => m.IemuTranDetailsModel.MainCode, (IEnumerable<SelectListItem>)Session["FirstLevelItems"], new { @class = "form-control" })
                        @Html.ValidationMessageFor(m => m.IemuTranDetailsModel.MainCode, "", new { @class = "text-danger" })
                    </div>
                </div>

                @* 中分類識別 *@
                <div class="row form-group mb-1">
                    @Html.LabelFor(m => m.IemuTranDetailsModel.ScId, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @* Jacky 1120807 第二層下拉選單內容因為會動態改變，所以這裡必須以 PartialView 的方式去整合動態資料並呈現之 *@
                        @Html.Partial("~/Views/PartialViews/_PartialSetSecondDropDownList.cshtml")
                        @Html.ValidationMessageFor(m => m.IemuTranDetailsModel.ScId, "", new { @class = "text-danger" })
                    </div>
                </div>

                @* 細分類序號 *@
                <div class="row form-group mb-1">
                    @Html.LabelFor(m => m.IemuTranDetailsModel.DetailOrder, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @* Jacky 1120807 第三層下拉選單內容因為會動態改變，所以這裡必須以 PartialView 的方式去整合動態資料並呈現之 *@
                        @Html.Partial("~/Views/PartialViews/_PartialSetThirdDropDownList.cshtml")
                        @Html.ValidationMessageFor(m => m.IemuTranDetailsModel.DetailOrder, "", new { @class = "text-danger" })
                    </div>
                </div>

                @* 備註 *@
                <div class="row form-group">
                    @Html.LabelFor(m => m.IemuTranDetailsModel.Remark, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(m => m.IemuTranDetailsModel.Remark, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(m => m.IemuTranDetailsModel.Remark, "", new { @class = "text-danger" })
                    </div>
                </div>

                <hr />
                <div class="row form-group mt-2">
                    <div class="col-12">
                        <input type="submit" value="確認編輯" class="btn btn-primary" title="確認編輯" />
                        @Html.ActionLink(ActionService.Return, ActionService.Index, ActionService.Controller,
                            new { area = "", id = ActionService.RowId },
                            new { @class = "btn btn-success" })
                    </div>
                </div>
            </div>
        }
    </div>
</div>

jb_tools/Views/IemuTranDetail/DynamicEdit.cshtml
@* Jacky 1120818 動態編輯 *@
@model jb_tools.Models.IemuTranDetails

@{
    ViewBag.Title = "動態編輯";
    Layout = "~/Views/Shared/_LayoutIEMenuMaker4.cshtml";
    ViewBag.FunctionAreaTitle = ViewBag.Title;

    // Jacky 1120727 記錄表頭 IemuTrans 的 No，以帶入表身
    ViewBag.IemuTranModel_No = Model.IemuTransModel.No;
}